### ISSUE TITLE
Nozzle Suggestion

### ISSUE THREAD

**Issue by UndisclosedBox83** [agehrke6/3D_printing#1]
I would like to suggest adding Trianglelab's high flow volcano style PCD nozzle to the list. The nozzle has a polycrystalline diamond tip, and the Plus version is a CHT style nozzle with three flow chambers. Below is the link:

https://www.aliexpress.us/item/3256805576915238.html

**Comment by agehrke6** [comment]
Added! thanks for the suggestions!

**Comment by UndisclosedBox83** [comment]
Some pictures for the curious.

![IMG_2906](https://github.com/agehrke6/3D_printing/assets/34873840/040fbe51-066e-4dcc-8b87-0379d5c43a03)
![IMG_2907](https://github.com/agehrke6/3D_printing/assets/34873840/ead0be27-5d95-4312-ab3d-275b2119c205)
![IMG_2908](https://github.com/agehrke6/3D_printing/assets/34873840/dec693f7-594b-4b77-8fc4-eccdc4759c40)
![IMG_2909](https://github.com/agehrke6/3D_printing/assets/34873840/6d857106-08fa-409c-9623-9b3d4e831d9d)
